Repository ConnectAI-E/Feishu-OpenAI, pull requests merged in 2023-03, with the labels that each got.

#40 chore: add binary release and Docker Hub support
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull-request-template.md
  .github/release-drafter.yml
  .github/workflows/binary-release.yml
  .github/workflows/docker-publish.yml
  .github/workflows/release-draft.yml
  readme.md
  s.yaml
Labels: chore

#41 feat: standardize the pr format to facilitate community participation
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhance_idea.md
  .github/ISSUE_TEMPLATE/error.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull-request-template.md
  .github/release-drafter.yml
  .github/workflows/docker-publish.yml
Labels: chore

#43 doc: add deployment instructions for binary installation files
  .github/FUNDING.yml
  readme.md
Labels: documentation

#47 doc: change issue template
  .github/ISSUE_TEMPLATE/enhance_idea.md
  .github/ISSUE_TEMPLATE/error.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/docker-publish.yml
Labels: documentation

#51 feat: support api for DALL.E
  code/handlers/group.go
  code/handlers/msg.go
  code/handlers/personal.go
  code/services/gpt3.go
  code/services/gpt3_test.go
  code/services/sessionCache.go
  code/utils/strings_test.go
Labels: enhancement

#55 chore: add Mac OS file filtering
  .gitignore
Labels: chore

#56 fix: session cache meta interface error
  code/services/sessionCache.go
Labels: fix

#57 docs: 增加windows下serverless部署教程
  readme.md
Labels: documentation

#64 refactor: kill if with chain of responsibility
  code/handlers/action.go
  code/handlers/group.go
  code/handlers/handler.go
  code/handlers/init.go
  code/handlers/msg.go
  code/handlers/personal.go
Labels: refactor

#67 feat: allow custom resolution and create multiple pic
  code/handlers/event_action.go
  code/handlers/handler.go
  code/handlers/msg.go
  code/services/sessionCache.go
Labels: enhancement

#74 refactor: improve server code quality by reorganizing cache and test code
  code/main.go
  code/services/gpt3.go
  code/services/gpt3_test.go
  code/services/msgCache.go
  code/services/sessionCache.go
Labels: refactor

#73 feat: support https and multi openai-keys to reduce access pressure
  .gitignore
  code/.gitignore
  code/config.example.yaml
  code/handlers/common.go
  code/handlers/handler.go
  code/handlers/init.go
  code/initialization/config.go
  code/initialization/gin.go
  code/main.go
  code/services/gpt3.go
  code/services/gpt3_test.go
  code/services/loadbalancer/loadbalancer.go
  entrypoint.sh
  readme.md
Labels: enhancement

#76 feat: support custom api domain for reverse proxy
  code/config.example.yaml
  code/initialization/config.go
  code/main.go
  code/services/gpt3.go
  code/services/gpt3_test.go
  entrypoint.sh
  readme.md
Labels: enhancement

#77 feat: adding support for custom proxies
  code/config.example.yaml
  code/initialization/config.go
  code/main.go
  code/services/gpt3.go
  code/services/gpt3_test.go
  entrypoint.sh
  readme.md
Labels: enhancement

#78 fix: null pointer generated when import cert file
  code/initialization/gin.go
Labels: fix

#82 fix: permission denied in entrypoint.sh script
  Dockerfile
Labels: fix

#83 feat: support voice talk
  code/go.mod
  code/go.sum
  code/handlers/common.go
  code/handlers/event_action.go
  code/handlers/handler.go
  code/handlers/init.go
  code/handlers/msg.go
  code/services/gpt3.go
  code/utils/audio/ogg.go
  code/utils/audio/wav.go
  readme.md
Labels: enhancement

#87 feat : support image variation
  code/handlers/common.go
  code/handlers/event_action.go
  code/handlers/handler.go
  code/handlers/init.go
  code/handlers/msg.go
  code/initialization/config.go
  code/main.go
  code/services/gpt3.go
  code/services/gpt3_test.go
  code/services/openai/audio.go
  code/services/openai/common.go
  code/services/openai/gpt3.go
  code/services/openai/gpt3_test.go
  code/services/openai/picture.go
  code/services/openai/test_file/img.png
  code/services/openai/test_file/test.jpg
  code/services/openai/test_file/test.wav
  code/services/sessionCache.go
Labels: enhancement

#88 fix: invalid picture resolution setting
  code/handlers/handler.go
Labels: fix

#127 refactor: remove entrypoint.sh to improve docker build and deploy
  Dockerfile
  code/config.example.yaml
  docker-compose.yaml
  entrypoint.sh
  readme.md
Labels: refactor

#133 feat: support built in role list
  code/go.mod
  code/go.sum
  code/handlers/card_clear_action.go
  code/handlers/card_common_action.go
  code/handlers/card_pic_action.go
  code/handlers/card_role_action.go
  code/handlers/event_common_action.go
  code/handlers/handler.go
  code/handlers/msg.go
  code/initialization/roles_load.go
  code/main.go
  code/role_list.yaml
  readme.md
Labels: enhancement

#147 fix: unicode characters show problem
  .github/workflows/binary-release.yml
  code/handlers/common.go
Labels: fix

#148 doc: optimized descrtiption about binary deployment section
  readme.md
Labels: documentation

#158 docs：role_list.yaml misleading content
  code/role_list.yaml
Labels: documentation
