Repository ConnectAI-E/Feishu-OpenAI, pull requests merged in 2023-04, with the labels that each got.

#176 doc: share free api for user test
  readme.md
Labels: documentation

#177 Feat: Support azure openai
  code/config.example.yaml
  code/handlers/event_audio_action.go
  code/handlers/event_pic_action.go
  code/handlers/handler.go
  code/initialization/config.go
  code/services/openai/audio.go
  code/services/openai/common.go
  code/services/openai/gpt3.go
  code/services/openai/gpt3_test.go
  code/services/openai/picture.go
  readme.md
Labels: enhancement

#179 fix: #178 goroutine nil pointer causes the service crash
  code/handlers/msg.go
Labels: bug

#197 ref: config.yaml AZURE_ON default set false
  code/config.example.yaml
Labels: chore
